### ISSUE TITLE
No update on StreamBuilder

### ISSUE THREAD

**Issue by greenvan** [thangmam/dynamic_treeview#1]
Hi, I really like this treeview but when data is from a stream source it builds ok at the begining but no updates when datastream changes. Any idea on how to implement it?
Sorry if it is a newbie question...

By the way, I'm trying to use it on a list of Expenses and Incomes categories and subcategories I retrieve from Firestore database. It shows the list perfect and beautiful at the begining. But when I add a new category the tree does not rebuild as the former listView does.

**Comment by thangmam** [comment]
Hello , when the stream source completes, you can pass the data from stream and rebuild it again.For example using setState. But since you are using firestore , only parts of it might be updated.You will need to fetch the whole data fully (not just parts of it).
You can store the data in some temp variable the first time it fetch from firestore and then build the tree using that data.When update/delete in firestore,you first update/delete the temp variable with the fresh data from firestore and then rebuild the tree.

**Comment by greenvan** [comment]
Hi! Thanks a lot for your response. Too busy at the moment with the Global pandemic situation to take a look earlier. 
I finally resolved this by adding an extra variable in the state class (called 'data' as well). 
I based this solution on this idea: [https://github.com/flutter/flutter/issues/20416]

In initState I initialize the variable with the value of widget.data. And then I override 'didUpdateWidget':


`  void initState() {
    data = widget.data;
    _buildTreeView();
    _childTapListener.addListener(childTapListener);
    super.initState();
  }

  void didUpdateWidget(DynamicTreeView oldWidget) {
    if (data != widget.data) {
      setState(() {
        data = widget.data;
        _buildTreeView();
      });
    }
    super.didUpdateWidget(oldWidget);
  }`
